services:
  solr:
    image: solr:9.8
    ports:
      - "1044:1044"  # Debugging port
      - "8983:8983"  # Solr admin interface
    volumes:
      - ./solr/install-plugin.sh:/docker-entrypoint-initdb.d/install-plugin.sh
      - ./solr/core:/opt/core-config
      - index-data:/var/solr
      - ./data:/data
      - ../target:/build
    environment:
      - ENABLE_REMOTE_JMX_OPTS=true
      - SOLR_HEAP=4g
      - ADDITIONAL_CMD_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:1044 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -XX:+PreserveFramePointer -Dsolr.config.lib.enabled=true
      - SOLR_SECURITY_MANAGER_ENABLED=false
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - ocr
      - /opt/core-config

  iiif-prezi:
    command: pipenv run prod
    build: iiif-prezi
    volumes:
      - ./data:/data
    environment:
      - CFG_SOLR_BASE=http://solr:8983/solr
      - CFG_IMAGE_API_BASE
      - CFG_LIBRARY_NAME
      - CFG_SERVER_URL
      - CFG_APP_PATH=/iiif/presentation
      - CFG_DIGILIB_PATH

  frontend:
    build:
      context: ./frontend
      args:
        CFG_IMAGE_API_BASE: ${CFG_IMAGE_API_BASE}
        CFG_LIBRARY_NAME: ${CFG_LIBRARY_NAME}
        CFG_SERVER_URL: ${CFG_SERVER_URL}
    environment:
      - CFG_IMAGE_API_BASE
      - CFG_LIBRARY_NAME
      - CFG_SERVER_URL
    ports:
      - "8181:80"
    depends_on:
      solr:
        condition: service_started
      iiif-prezi:
        condition: service_started

volumes:
  index-data:
